#include "vct/voxels.glsl"

layout(std430, binding = 1) coherent readonly buffer HeaderPointers {
	int headerPointers[];
};

layout(std430, binding = 2) coherent writeonly buffer ActiveBricks {
	int brickIDs[];
};

uniform int bricksPerAxis; 
uniform int brickDimension; 
uniform int volumeDimension; 

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
void main() {
	ivec3 voxelCoord = ivec3(gl_GlobalInvocationID.xyz);

	// Out of bounds guard
	if (voxelCoord.x >= volumeDimension ||
		voxelCoord.y >= volumeDimension ||
		voxelCoord.z >= volumeDimension) {

		return;
	}

	// Flatten voxel index
	int voxelIndex = getFlattenedIndex(voxelCoord, volumeDimension);

	// If this voxel has no nodes, skip
	if (headerPointers[voxelIndex] == -1) {
		return;
	}

	// Compute brick cell coordinate (integer division)
	ivec3 brickCoord = ivec3(voxelCoord) / brickDimension;

	// Flatten brick cell index
	int brickIndex = getFlattenedIndex(brickCoord, bricksPerAxis);

	// Mark brick as active
	// No need for CAS — OR is enough because 1 means "active"
	brickIDs[brickIndex] = 1;
}

