
layout(binding = 0, r16f) uniform image2D dst;

layout(binding = 1) uniform sampler2D src;
uniform vec2 textureDimensions;
uniform int currentMip;

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;
void main() {
	float depth = textureLod(src, vec2(gl_GlobalInvocationID.xy / textureDimensions), currentMip-1).r;
	imageStore(dst, ivec2(gl_GlobalInvocationID.xy), vec4(depth, 0, 0, 1));
}