#pragma once

#include "ECS/Component/Component.hpp"

namespace CSM {
	START_COMPONENT(CSMCamera0);
	END_COMPONENT();
	START_COMPONENT(CSMCamera1);
	END_COMPONENT();
	START_COMPONENT(CSMCamera2);
	END_COMPONENT();
	START_COMPONENT(CSMCamera3);
	END_COMPONENT();
}