
layout(binding = 1, std430) writeonly buffer histogramBuffer {
    uint histogram[];
};

#ifndef CLEAR
layout(binding = 0, rgba16f) readonly uniform image2D inputTexture;
#endif

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
void main() {
    
#ifdef CLEAR
    histogram[gl_LocalInvocationIndex] = 0;
    return;
#endif

    histogram[gl_LocalInvocationIndex] = gl_LocalInvocationIndex;
}